name: Deploy to npm

on:
  push:
    branches: [ dev ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install    
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          tag: test
          token: ${{ secrets.NPM_TOKEN }}
          