name: Continuous Integration

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run test
      - run: npm run build
